sudo: false
language: python
dist: focal
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.9"
      env: TOXENV=black
    - python: "3.9"
      env: TOXENV=flake8
install:
  - pip install -U tox coveralls
script:
  - tox
cache: pip
after_success:
  - coveralls